/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as MembersRouteImport } from './routes/members'
import { Route as HealthRouteImport } from './routes/health'
import { Route as DeactivatedRouteImport } from './routes/deactivated'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MembersIndexRouteImport } from './routes/members.index'
import { Route as AccountIndexRouteImport } from './routes/account.index'
import { Route as RegisterProfileRouteImport } from './routes/register.profile'
import { Route as RegisterPendingRouteImport } from './routes/register.pending'
import { Route as MembersRolesRouteImport } from './routes/members.roles'
import { Route as MembersRegistrationsRouteImport } from './routes/members.registrations'
import { Route as MembersUserIdRouteImport } from './routes/members.$userId'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AccountSecurityRouteImport } from './routes/account.security'
import { Route as AccountPreferencesRouteImport } from './routes/account.preferences'
import { Route as AccountDetailsRouteImport } from './routes/account.details'
import { Route as MembersRolesRoleIdRouteImport } from './routes/members.roles_.$roleId'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const DeactivatedRoute = DeactivatedRouteImport.update({
  id: '/deactivated',
  path: '/deactivated',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersIndexRoute = MembersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembersRoute,
} as any)
const AccountIndexRoute = AccountIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountRoute,
} as any)
const RegisterProfileRoute = RegisterProfileRouteImport.update({
  id: '/register/profile',
  path: '/register/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterPendingRoute = RegisterPendingRouteImport.update({
  id: '/register/pending',
  path: '/register/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRolesRoute = MembersRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => MembersRoute,
} as any)
const MembersRegistrationsRoute = MembersRegistrationsRouteImport.update({
  id: '/registrations',
  path: '/registrations',
  getParentRoute: () => MembersRoute,
} as any)
const MembersUserIdRoute = MembersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => MembersRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSecurityRoute = AccountSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => AccountRoute,
} as any)
const AccountPreferencesRoute = AccountPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => AccountRoute,
} as any)
const AccountDetailsRoute = AccountDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => AccountRoute,
} as any)
const MembersRolesRoleIdRoute = MembersRolesRoleIdRouteImport.update({
  id: '/roles_/$roleId',
  path: '/roles/$roleId',
  getParentRoute: () => MembersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/deactivated': typeof DeactivatedRoute
  '/health': typeof HealthRoute
  '/members': typeof MembersRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/account/details': typeof AccountDetailsRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/security': typeof AccountSecurityRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/members/$userId': typeof MembersUserIdRoute
  '/members/registrations': typeof MembersRegistrationsRoute
  '/members/roles': typeof MembersRolesRoute
  '/register/pending': typeof RegisterPendingRoute
  '/register/profile': typeof RegisterProfileRoute
  '/account/': typeof AccountIndexRoute
  '/members/': typeof MembersIndexRoute
  '/members/roles/$roleId': typeof MembersRolesRoleIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/deactivated': typeof DeactivatedRoute
  '/health': typeof HealthRoute
  '/sign-in': typeof SignInRoute
  '/account/details': typeof AccountDetailsRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/security': typeof AccountSecurityRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/members/$userId': typeof MembersUserIdRoute
  '/members/registrations': typeof MembersRegistrationsRoute
  '/members/roles': typeof MembersRolesRoute
  '/register/pending': typeof RegisterPendingRoute
  '/register/profile': typeof RegisterProfileRoute
  '/account': typeof AccountIndexRoute
  '/members': typeof MembersIndexRoute
  '/members/roles/$roleId': typeof MembersRolesRoleIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/deactivated': typeof DeactivatedRoute
  '/health': typeof HealthRoute
  '/members': typeof MembersRouteWithChildren
  '/sign-in': typeof SignInRoute
  '/account/details': typeof AccountDetailsRoute
  '/account/preferences': typeof AccountPreferencesRoute
  '/account/security': typeof AccountSecurityRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/members/$userId': typeof MembersUserIdRoute
  '/members/registrations': typeof MembersRegistrationsRoute
  '/members/roles': typeof MembersRolesRoute
  '/register/pending': typeof RegisterPendingRoute
  '/register/profile': typeof RegisterProfileRoute
  '/account/': typeof AccountIndexRoute
  '/members/': typeof MembersIndexRoute
  '/members/roles_/$roleId': typeof MembersRolesRoleIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/deactivated'
    | '/health'
    | '/members'
    | '/sign-in'
    | '/account/details'
    | '/account/preferences'
    | '/account/security'
    | '/auth/callback'
    | '/members/$userId'
    | '/members/registrations'
    | '/members/roles'
    | '/register/pending'
    | '/register/profile'
    | '/account/'
    | '/members/'
    | '/members/roles/$roleId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/deactivated'
    | '/health'
    | '/sign-in'
    | '/account/details'
    | '/account/preferences'
    | '/account/security'
    | '/auth/callback'
    | '/members/$userId'
    | '/members/registrations'
    | '/members/roles'
    | '/register/pending'
    | '/register/profile'
    | '/account'
    | '/members'
    | '/members/roles/$roleId'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/deactivated'
    | '/health'
    | '/members'
    | '/sign-in'
    | '/account/details'
    | '/account/preferences'
    | '/account/security'
    | '/auth/callback'
    | '/members/$userId'
    | '/members/registrations'
    | '/members/roles'
    | '/register/pending'
    | '/register/profile'
    | '/account/'
    | '/members/'
    | '/members/roles_/$roleId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  DeactivatedRoute: typeof DeactivatedRoute
  HealthRoute: typeof HealthRoute
  MembersRoute: typeof MembersRouteWithChildren
  SignInRoute: typeof SignInRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  RegisterPendingRoute: typeof RegisterPendingRoute
  RegisterProfileRoute: typeof RegisterProfileRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deactivated': {
      id: '/deactivated'
      path: '/deactivated'
      fullPath: '/deactivated'
      preLoaderRoute: typeof DeactivatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/': {
      id: '/members/'
      path: '/'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersIndexRouteImport
      parentRoute: typeof MembersRoute
    }
    '/account/': {
      id: '/account/'
      path: '/'
      fullPath: '/account/'
      preLoaderRoute: typeof AccountIndexRouteImport
      parentRoute: typeof AccountRoute
    }
    '/register/profile': {
      id: '/register/profile'
      path: '/register/profile'
      fullPath: '/register/profile'
      preLoaderRoute: typeof RegisterProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/pending': {
      id: '/register/pending'
      path: '/register/pending'
      fullPath: '/register/pending'
      preLoaderRoute: typeof RegisterPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members/roles': {
      id: '/members/roles'
      path: '/roles'
      fullPath: '/members/roles'
      preLoaderRoute: typeof MembersRolesRouteImport
      parentRoute: typeof MembersRoute
    }
    '/members/registrations': {
      id: '/members/registrations'
      path: '/registrations'
      fullPath: '/members/registrations'
      preLoaderRoute: typeof MembersRegistrationsRouteImport
      parentRoute: typeof MembersRoute
    }
    '/members/$userId': {
      id: '/members/$userId'
      path: '/$userId'
      fullPath: '/members/$userId'
      preLoaderRoute: typeof MembersUserIdRouteImport
      parentRoute: typeof MembersRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/security': {
      id: '/account/security'
      path: '/security'
      fullPath: '/account/security'
      preLoaderRoute: typeof AccountSecurityRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/preferences': {
      id: '/account/preferences'
      path: '/preferences'
      fullPath: '/account/preferences'
      preLoaderRoute: typeof AccountPreferencesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/details': {
      id: '/account/details'
      path: '/details'
      fullPath: '/account/details'
      preLoaderRoute: typeof AccountDetailsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/members/roles_/$roleId': {
      id: '/members/roles_/$roleId'
      path: '/roles/$roleId'
      fullPath: '/members/roles/$roleId'
      preLoaderRoute: typeof MembersRolesRoleIdRouteImport
      parentRoute: typeof MembersRoute
    }
  }
}

interface AccountRouteChildren {
  AccountDetailsRoute: typeof AccountDetailsRoute
  AccountPreferencesRoute: typeof AccountPreferencesRoute
  AccountSecurityRoute: typeof AccountSecurityRoute
  AccountIndexRoute: typeof AccountIndexRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountDetailsRoute: AccountDetailsRoute,
  AccountPreferencesRoute: AccountPreferencesRoute,
  AccountSecurityRoute: AccountSecurityRoute,
  AccountIndexRoute: AccountIndexRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface MembersRouteChildren {
  MembersUserIdRoute: typeof MembersUserIdRoute
  MembersRegistrationsRoute: typeof MembersRegistrationsRoute
  MembersRolesRoute: typeof MembersRolesRoute
  MembersIndexRoute: typeof MembersIndexRoute
  MembersRolesRoleIdRoute: typeof MembersRolesRoleIdRoute
}

const MembersRouteChildren: MembersRouteChildren = {
  MembersUserIdRoute: MembersUserIdRoute,
  MembersRegistrationsRoute: MembersRegistrationsRoute,
  MembersRolesRoute: MembersRolesRoute,
  MembersIndexRoute: MembersIndexRoute,
  MembersRolesRoleIdRoute: MembersRolesRoleIdRoute,
}

const MembersRouteWithChildren =
  MembersRoute._addFileChildren(MembersRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  DeactivatedRoute: DeactivatedRoute,
  HealthRoute: HealthRoute,
  MembersRoute: MembersRouteWithChildren,
  SignInRoute: SignInRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  RegisterPendingRoute: RegisterPendingRoute,
  RegisterProfileRoute: RegisterProfileRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
