/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WaiverRouteImport } from './routes/waiver'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as OpenSourceRouteImport } from './routes/open-source'
import { Route as NondiscriminationRouteImport } from './routes/nondiscrimination'
import { Route as MyRouteImport } from './routes/my'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as MembersRouteImport } from './routes/members'
import { Route as LegalRouteImport } from './routes/legal'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as HealthRouteImport } from './routes/health'
import { Route as GearCaveRouteImport } from './routes/gear-cave'
import { Route as GearRouteImport } from './routes/gear'
import { Route as GazetteRouteImport } from './routes/gazette'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DisclaimerRouteImport } from './routes/disclaimer'
import { Route as DeactivatedRouteImport } from './routes/deactivated'
import { Route as ConstitutionRouteImport } from './routes/constitution'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as AntiHazingRouteImport } from './routes/anti-hazing'
import { Route as AlbumRouteImport } from './routes/album'
import { Route as AccessRouteImport } from './routes/access'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyIndexRouteImport } from './routes/my.index'
import { Route as GearIndexRouteImport } from './routes/gear.index'
import { Route as GazetteIndexRouteImport } from './routes/gazette.index'
import { Route as AnnouncementsIndexRouteImport } from './routes/announcements.index'
import { Route as RegisterProfileRouteImport } from './routes/register.profile'
import { Route as RegisterPendingRouteImport } from './routes/register.pending'
import { Route as MyGearRouteImport } from './routes/my.gear'
import { Route as MyTabsRouteImport } from './routes/my._tabs'
import { Route as MembersWaiversRouteImport } from './routes/members.waivers'
import { Route as MembersTabsRouteImport } from './routes/members._tabs'
import { Route as MembersPublicIdRouteImport } from './routes/members.$publicId'
import { Route as GearPublicIdRouteImport } from './routes/gear.$publicId'
import { Route as GazettePublicIdRouteImport } from './routes/gazette.$publicId'
import { Route as FeedbackTabsRouteImport } from './routes/feedback._tabs'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as MyGearIndexRouteImport } from './routes/my.gear.index'
import { Route as MembersTabsIndexRouteImport } from './routes/members._tabs.index'
import { Route as GearLoansIndexRouteImport } from './routes/gear.loans.index'
import { Route as FeedbackTabsIndexRouteImport } from './routes/feedback._tabs.index'
import { Route as MyGearCartRouteImport } from './routes/my.gear.cart'
import { Route as MyTabsWaiverRouteImport } from './routes/my._tabs.waiver'
import { Route as MyTabsSecurityRouteImport } from './routes/my._tabs.security'
import { Route as MyTabsProfileRouteImport } from './routes/my._tabs.profile'
import { Route as MyTabsPreferencesRouteImport } from './routes/my._tabs.preferences'
import { Route as MyTabsDetailsRouteImport } from './routes/my._tabs.details'
import { Route as MyTabsContactsRouteImport } from './routes/my._tabs.contacts'
import { Route as MembersTabsUnclaimedRouteImport } from './routes/members._tabs.unclaimed'
import { Route as MembersTabsRejectedRouteImport } from './routes/members._tabs.rejected'
import { Route as MembersTabsPendingRouteImport } from './routes/members._tabs.pending'
import { Route as MembersTabsDeactivatedRouteImport } from './routes/members._tabs.deactivated'
import { Route as GearLoansPublicIdRouteImport } from './routes/gear.loans.$publicId'
import { Route as FeedbackTabsClubRouteImport } from './routes/feedback._tabs.club'
import { Route as ApiLandingSplatRouteImport } from './routes/api/landing.$'
import { Route as ApiGearThumbnailsSplatRouteImport } from './routes/api/gear-thumbnails.$'
import { Route as ApiGazettePdfSplatRouteImport } from './routes/api/gazette-pdf.$'
import { Route as ApiAvatarsSplatRouteImport } from './routes/api/avatars.$'
import { Route as ApiAlbumImageSplatRouteImport } from './routes/api/album-image.$'
import { Route as ApiAccountExportRouteImport } from './routes/api/account.export'

const WaiverRoute = WaiverRouteImport.update({
  id: '/waiver',
  path: '/waiver',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const OpenSourceRoute = OpenSourceRouteImport.update({
  id: '/open-source',
  path: '/open-source',
  getParentRoute: () => rootRouteImport,
} as any)
const NondiscriminationRoute = NondiscriminationRouteImport.update({
  id: '/nondiscrimination',
  path: '/nondiscrimination',
  getParentRoute: () => rootRouteImport,
} as any)
const MyRoute = MyRouteImport.update({
  id: '/my',
  path: '/my',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const MembersRoute = MembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRoute = LegalRouteImport.update({
  id: '/legal',
  path: '/legal',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const GearCaveRoute = GearCaveRouteImport.update({
  id: '/gear-cave',
  path: '/gear-cave',
  getParentRoute: () => rootRouteImport,
} as any)
const GearRoute = GearRouteImport.update({
  id: '/gear',
  path: '/gear',
  getParentRoute: () => rootRouteImport,
} as any)
const GazetteRoute = GazetteRouteImport.update({
  id: '/gazette',
  path: '/gazette',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DisclaimerRoute = DisclaimerRouteImport.update({
  id: '/disclaimer',
  path: '/disclaimer',
  getParentRoute: () => rootRouteImport,
} as any)
const DeactivatedRoute = DeactivatedRouteImport.update({
  id: '/deactivated',
  path: '/deactivated',
  getParentRoute: () => rootRouteImport,
} as any)
const ConstitutionRoute = ConstitutionRouteImport.update({
  id: '/constitution',
  path: '/constitution',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AntiHazingRoute = AntiHazingRouteImport.update({
  id: '/anti-hazing',
  path: '/anti-hazing',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumRoute = AlbumRouteImport.update({
  id: '/album',
  path: '/album',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRoute = AccessRouteImport.update({
  id: '/access',
  path: '/access',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyIndexRoute = MyIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyRoute,
} as any)
const GearIndexRoute = GearIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GearRoute,
} as any)
const GazetteIndexRoute = GazetteIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GazetteRoute,
} as any)
const AnnouncementsIndexRoute = AnnouncementsIndexRouteImport.update({
  id: '/announcements/',
  path: '/announcements/',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterProfileRoute = RegisterProfileRouteImport.update({
  id: '/register/profile',
  path: '/register/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterPendingRoute = RegisterPendingRouteImport.update({
  id: '/register/pending',
  path: '/register/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const MyGearRoute = MyGearRouteImport.update({
  id: '/gear',
  path: '/gear',
  getParentRoute: () => MyRoute,
} as any)
const MyTabsRoute = MyTabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => MyRoute,
} as any)
const MembersWaiversRoute = MembersWaiversRouteImport.update({
  id: '/waivers',
  path: '/waivers',
  getParentRoute: () => MembersRoute,
} as any)
const MembersTabsRoute = MembersTabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => MembersRoute,
} as any)
const MembersPublicIdRoute = MembersPublicIdRouteImport.update({
  id: '/$publicId',
  path: '/$publicId',
  getParentRoute: () => MembersRoute,
} as any)
const GearPublicIdRoute = GearPublicIdRouteImport.update({
  id: '/$publicId',
  path: '/$publicId',
  getParentRoute: () => GearRoute,
} as any)
const GazettePublicIdRoute = GazettePublicIdRouteImport.update({
  id: '/$publicId',
  path: '/$publicId',
  getParentRoute: () => GazetteRoute,
} as any)
const FeedbackTabsRoute = FeedbackTabsRouteImport.update({
  id: '/_tabs',
  getParentRoute: () => FeedbackRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const MyGearIndexRoute = MyGearIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyGearRoute,
} as any)
const MembersTabsIndexRoute = MembersTabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MembersTabsRoute,
} as any)
const GearLoansIndexRoute = GearLoansIndexRouteImport.update({
  id: '/loans/',
  path: '/loans/',
  getParentRoute: () => GearRoute,
} as any)
const FeedbackTabsIndexRoute = FeedbackTabsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FeedbackTabsRoute,
} as any)
const MyGearCartRoute = MyGearCartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => MyGearRoute,
} as any)
const MyTabsWaiverRoute = MyTabsWaiverRouteImport.update({
  id: '/waiver',
  path: '/waiver',
  getParentRoute: () => MyTabsRoute,
} as any)
const MyTabsSecurityRoute = MyTabsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => MyTabsRoute,
} as any)
const MyTabsProfileRoute = MyTabsProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => MyTabsRoute,
} as any)
const MyTabsPreferencesRoute = MyTabsPreferencesRouteImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => MyTabsRoute,
} as any)
const MyTabsDetailsRoute = MyTabsDetailsRouteImport.update({
  id: '/details',
  path: '/details',
  getParentRoute: () => MyTabsRoute,
} as any)
const MyTabsContactsRoute = MyTabsContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => MyTabsRoute,
} as any)
const MembersTabsUnclaimedRoute = MembersTabsUnclaimedRouteImport.update({
  id: '/unclaimed',
  path: '/unclaimed',
  getParentRoute: () => MembersTabsRoute,
} as any)
const MembersTabsRejectedRoute = MembersTabsRejectedRouteImport.update({
  id: '/rejected',
  path: '/rejected',
  getParentRoute: () => MembersTabsRoute,
} as any)
const MembersTabsPendingRoute = MembersTabsPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => MembersTabsRoute,
} as any)
const MembersTabsDeactivatedRoute = MembersTabsDeactivatedRouteImport.update({
  id: '/deactivated',
  path: '/deactivated',
  getParentRoute: () => MembersTabsRoute,
} as any)
const GearLoansPublicIdRoute = GearLoansPublicIdRouteImport.update({
  id: '/loans/$publicId',
  path: '/loans/$publicId',
  getParentRoute: () => GearRoute,
} as any)
const FeedbackTabsClubRoute = FeedbackTabsClubRouteImport.update({
  id: '/club',
  path: '/club',
  getParentRoute: () => FeedbackTabsRoute,
} as any)
const ApiLandingSplatRoute = ApiLandingSplatRouteImport.update({
  id: '/api/landing/$',
  path: '/api/landing/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGearThumbnailsSplatRoute = ApiGearThumbnailsSplatRouteImport.update({
  id: '/api/gear-thumbnails/$',
  path: '/api/gear-thumbnails/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGazettePdfSplatRoute = ApiGazettePdfSplatRouteImport.update({
  id: '/api/gazette-pdf/$',
  path: '/api/gazette-pdf/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAvatarsSplatRoute = ApiAvatarsSplatRouteImport.update({
  id: '/api/avatars/$',
  path: '/api/avatars/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlbumImageSplatRoute = ApiAlbumImageSplatRouteImport.update({
  id: '/api/album-image/$',
  path: '/api/album-image/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAccountExportRoute = ApiAccountExportRouteImport.update({
  id: '/api/account/export',
  path: '/api/account/export',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/access': typeof AccessRoute
  '/album': typeof AlbumRoute
  '/anti-hazing': typeof AntiHazingRoute
  '/audit': typeof AuditRoute
  '/constitution': typeof ConstitutionRoute
  '/deactivated': typeof DeactivatedRoute
  '/disclaimer': typeof DisclaimerRoute
  '/feedback': typeof FeedbackRouteWithChildren
  '/gazette': typeof GazetteRouteWithChildren
  '/gear': typeof GearRouteWithChildren
  '/gear-cave': typeof GearCaveRoute
  '/health': typeof HealthRoute
  '/history': typeof HistoryRoute
  '/legal': typeof LegalRoute
  '/members': typeof MembersRouteWithChildren
  '/membership': typeof MembershipRoute
  '/my': typeof MyRouteWithChildren
  '/nondiscrimination': typeof NondiscriminationRoute
  '/open-source': typeof OpenSourceRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/scholarships': typeof ScholarshipsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/waiver': typeof WaiverRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/gazette/$publicId': typeof GazettePublicIdRoute
  '/gear/$publicId': typeof GearPublicIdRoute
  '/members/$publicId': typeof MembersPublicIdRoute
  '/members/waivers': typeof MembersWaiversRoute
  '/my/gear': typeof MyGearRouteWithChildren
  '/register/pending': typeof RegisterPendingRoute
  '/register/profile': typeof RegisterProfileRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/gazette/': typeof GazetteIndexRoute
  '/gear/': typeof GearIndexRoute
  '/my/': typeof MyIndexRoute
  '/api/account/export': typeof ApiAccountExportRoute
  '/api/album-image/$': typeof ApiAlbumImageSplatRoute
  '/api/avatars/$': typeof ApiAvatarsSplatRoute
  '/api/gazette-pdf/$': typeof ApiGazettePdfSplatRoute
  '/api/gear-thumbnails/$': typeof ApiGearThumbnailsSplatRoute
  '/api/landing/$': typeof ApiLandingSplatRoute
  '/feedback/club': typeof FeedbackTabsClubRoute
  '/gear/loans/$publicId': typeof GearLoansPublicIdRoute
  '/members/deactivated': typeof MembersTabsDeactivatedRoute
  '/members/pending': typeof MembersTabsPendingRoute
  '/members/rejected': typeof MembersTabsRejectedRoute
  '/members/unclaimed': typeof MembersTabsUnclaimedRoute
  '/my/contacts': typeof MyTabsContactsRoute
  '/my/details': typeof MyTabsDetailsRoute
  '/my/preferences': typeof MyTabsPreferencesRoute
  '/my/profile': typeof MyTabsProfileRoute
  '/my/security': typeof MyTabsSecurityRoute
  '/my/waiver': typeof MyTabsWaiverRoute
  '/my/gear/cart': typeof MyGearCartRoute
  '/feedback/': typeof FeedbackTabsIndexRoute
  '/gear/loans/': typeof GearLoansIndexRoute
  '/members/': typeof MembersTabsIndexRoute
  '/my/gear/': typeof MyGearIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/access': typeof AccessRoute
  '/album': typeof AlbumRoute
  '/anti-hazing': typeof AntiHazingRoute
  '/audit': typeof AuditRoute
  '/constitution': typeof ConstitutionRoute
  '/deactivated': typeof DeactivatedRoute
  '/disclaimer': typeof DisclaimerRoute
  '/feedback': typeof FeedbackTabsIndexRoute
  '/gear-cave': typeof GearCaveRoute
  '/health': typeof HealthRoute
  '/history': typeof HistoryRoute
  '/legal': typeof LegalRoute
  '/members': typeof MembersTabsIndexRoute
  '/membership': typeof MembershipRoute
  '/nondiscrimination': typeof NondiscriminationRoute
  '/open-source': typeof OpenSourceRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/scholarships': typeof ScholarshipsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/waiver': typeof WaiverRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/gazette/$publicId': typeof GazettePublicIdRoute
  '/gear/$publicId': typeof GearPublicIdRoute
  '/members/$publicId': typeof MembersPublicIdRoute
  '/members/waivers': typeof MembersWaiversRoute
  '/my': typeof MyIndexRoute
  '/register/pending': typeof RegisterPendingRoute
  '/register/profile': typeof RegisterProfileRoute
  '/announcements': typeof AnnouncementsIndexRoute
  '/gazette': typeof GazetteIndexRoute
  '/gear': typeof GearIndexRoute
  '/api/account/export': typeof ApiAccountExportRoute
  '/api/album-image/$': typeof ApiAlbumImageSplatRoute
  '/api/avatars/$': typeof ApiAvatarsSplatRoute
  '/api/gazette-pdf/$': typeof ApiGazettePdfSplatRoute
  '/api/gear-thumbnails/$': typeof ApiGearThumbnailsSplatRoute
  '/api/landing/$': typeof ApiLandingSplatRoute
  '/feedback/club': typeof FeedbackTabsClubRoute
  '/gear/loans/$publicId': typeof GearLoansPublicIdRoute
  '/members/deactivated': typeof MembersTabsDeactivatedRoute
  '/members/pending': typeof MembersTabsPendingRoute
  '/members/rejected': typeof MembersTabsRejectedRoute
  '/members/unclaimed': typeof MembersTabsUnclaimedRoute
  '/my/contacts': typeof MyTabsContactsRoute
  '/my/details': typeof MyTabsDetailsRoute
  '/my/preferences': typeof MyTabsPreferencesRoute
  '/my/profile': typeof MyTabsProfileRoute
  '/my/security': typeof MyTabsSecurityRoute
  '/my/waiver': typeof MyTabsWaiverRoute
  '/my/gear/cart': typeof MyGearCartRoute
  '/gear/loans': typeof GearLoansIndexRoute
  '/my/gear': typeof MyGearIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/access': typeof AccessRoute
  '/album': typeof AlbumRoute
  '/anti-hazing': typeof AntiHazingRoute
  '/audit': typeof AuditRoute
  '/constitution': typeof ConstitutionRoute
  '/deactivated': typeof DeactivatedRoute
  '/disclaimer': typeof DisclaimerRoute
  '/feedback': typeof FeedbackRouteWithChildren
  '/gazette': typeof GazetteRouteWithChildren
  '/gear': typeof GearRouteWithChildren
  '/gear-cave': typeof GearCaveRoute
  '/health': typeof HealthRoute
  '/history': typeof HistoryRoute
  '/legal': typeof LegalRoute
  '/members': typeof MembersRouteWithChildren
  '/membership': typeof MembershipRoute
  '/my': typeof MyRouteWithChildren
  '/nondiscrimination': typeof NondiscriminationRoute
  '/open-source': typeof OpenSourceRoute
  '/policies': typeof PoliciesRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/scholarships': typeof ScholarshipsRoute
  '/settings': typeof SettingsRoute
  '/sign-in': typeof SignInRoute
  '/terms': typeof TermsRoute
  '/verify-email': typeof VerifyEmailRoute
  '/waiver': typeof WaiverRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/feedback/_tabs': typeof FeedbackTabsRouteWithChildren
  '/gazette/$publicId': typeof GazettePublicIdRoute
  '/gear/$publicId': typeof GearPublicIdRoute
  '/members/$publicId': typeof MembersPublicIdRoute
  '/members/_tabs': typeof MembersTabsRouteWithChildren
  '/members/waivers': typeof MembersWaiversRoute
  '/my/_tabs': typeof MyTabsRouteWithChildren
  '/my/gear': typeof MyGearRouteWithChildren
  '/register/pending': typeof RegisterPendingRoute
  '/register/profile': typeof RegisterProfileRoute
  '/announcements/': typeof AnnouncementsIndexRoute
  '/gazette/': typeof GazetteIndexRoute
  '/gear/': typeof GearIndexRoute
  '/my/': typeof MyIndexRoute
  '/api/account/export': typeof ApiAccountExportRoute
  '/api/album-image/$': typeof ApiAlbumImageSplatRoute
  '/api/avatars/$': typeof ApiAvatarsSplatRoute
  '/api/gazette-pdf/$': typeof ApiGazettePdfSplatRoute
  '/api/gear-thumbnails/$': typeof ApiGearThumbnailsSplatRoute
  '/api/landing/$': typeof ApiLandingSplatRoute
  '/feedback/_tabs/club': typeof FeedbackTabsClubRoute
  '/gear/loans/$publicId': typeof GearLoansPublicIdRoute
  '/members/_tabs/deactivated': typeof MembersTabsDeactivatedRoute
  '/members/_tabs/pending': typeof MembersTabsPendingRoute
  '/members/_tabs/rejected': typeof MembersTabsRejectedRoute
  '/members/_tabs/unclaimed': typeof MembersTabsUnclaimedRoute
  '/my/_tabs/contacts': typeof MyTabsContactsRoute
  '/my/_tabs/details': typeof MyTabsDetailsRoute
  '/my/_tabs/preferences': typeof MyTabsPreferencesRoute
  '/my/_tabs/profile': typeof MyTabsProfileRoute
  '/my/_tabs/security': typeof MyTabsSecurityRoute
  '/my/_tabs/waiver': typeof MyTabsWaiverRoute
  '/my/gear/cart': typeof MyGearCartRoute
  '/feedback/_tabs/': typeof FeedbackTabsIndexRoute
  '/gear/loans/': typeof GearLoansIndexRoute
  '/members/_tabs/': typeof MembersTabsIndexRoute
  '/my/gear/': typeof MyGearIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/access'
    | '/album'
    | '/anti-hazing'
    | '/audit'
    | '/constitution'
    | '/deactivated'
    | '/disclaimer'
    | '/feedback'
    | '/gazette'
    | '/gear'
    | '/gear-cave'
    | '/health'
    | '/history'
    | '/legal'
    | '/members'
    | '/membership'
    | '/my'
    | '/nondiscrimination'
    | '/open-source'
    | '/policies'
    | '/privacy'
    | '/resources'
    | '/scholarships'
    | '/settings'
    | '/sign-in'
    | '/terms'
    | '/verify-email'
    | '/waiver'
    | '/auth/callback'
    | '/gazette/$publicId'
    | '/gear/$publicId'
    | '/members/$publicId'
    | '/members/waivers'
    | '/my/gear'
    | '/register/pending'
    | '/register/profile'
    | '/announcements/'
    | '/gazette/'
    | '/gear/'
    | '/my/'
    | '/api/account/export'
    | '/api/album-image/$'
    | '/api/avatars/$'
    | '/api/gazette-pdf/$'
    | '/api/gear-thumbnails/$'
    | '/api/landing/$'
    | '/feedback/club'
    | '/gear/loans/$publicId'
    | '/members/deactivated'
    | '/members/pending'
    | '/members/rejected'
    | '/members/unclaimed'
    | '/my/contacts'
    | '/my/details'
    | '/my/preferences'
    | '/my/profile'
    | '/my/security'
    | '/my/waiver'
    | '/my/gear/cart'
    | '/feedback/'
    | '/gear/loans/'
    | '/members/'
    | '/my/gear/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/access'
    | '/album'
    | '/anti-hazing'
    | '/audit'
    | '/constitution'
    | '/deactivated'
    | '/disclaimer'
    | '/feedback'
    | '/gear-cave'
    | '/health'
    | '/history'
    | '/legal'
    | '/members'
    | '/membership'
    | '/nondiscrimination'
    | '/open-source'
    | '/policies'
    | '/privacy'
    | '/resources'
    | '/scholarships'
    | '/settings'
    | '/sign-in'
    | '/terms'
    | '/verify-email'
    | '/waiver'
    | '/auth/callback'
    | '/gazette/$publicId'
    | '/gear/$publicId'
    | '/members/$publicId'
    | '/members/waivers'
    | '/my'
    | '/register/pending'
    | '/register/profile'
    | '/announcements'
    | '/gazette'
    | '/gear'
    | '/api/account/export'
    | '/api/album-image/$'
    | '/api/avatars/$'
    | '/api/gazette-pdf/$'
    | '/api/gear-thumbnails/$'
    | '/api/landing/$'
    | '/feedback/club'
    | '/gear/loans/$publicId'
    | '/members/deactivated'
    | '/members/pending'
    | '/members/rejected'
    | '/members/unclaimed'
    | '/my/contacts'
    | '/my/details'
    | '/my/preferences'
    | '/my/profile'
    | '/my/security'
    | '/my/waiver'
    | '/my/gear/cart'
    | '/gear/loans'
    | '/my/gear'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/access'
    | '/album'
    | '/anti-hazing'
    | '/audit'
    | '/constitution'
    | '/deactivated'
    | '/disclaimer'
    | '/feedback'
    | '/gazette'
    | '/gear'
    | '/gear-cave'
    | '/health'
    | '/history'
    | '/legal'
    | '/members'
    | '/membership'
    | '/my'
    | '/nondiscrimination'
    | '/open-source'
    | '/policies'
    | '/privacy'
    | '/resources'
    | '/scholarships'
    | '/settings'
    | '/sign-in'
    | '/terms'
    | '/verify-email'
    | '/waiver'
    | '/auth/callback'
    | '/feedback/_tabs'
    | '/gazette/$publicId'
    | '/gear/$publicId'
    | '/members/$publicId'
    | '/members/_tabs'
    | '/members/waivers'
    | '/my/_tabs'
    | '/my/gear'
    | '/register/pending'
    | '/register/profile'
    | '/announcements/'
    | '/gazette/'
    | '/gear/'
    | '/my/'
    | '/api/account/export'
    | '/api/album-image/$'
    | '/api/avatars/$'
    | '/api/gazette-pdf/$'
    | '/api/gear-thumbnails/$'
    | '/api/landing/$'
    | '/feedback/_tabs/club'
    | '/gear/loans/$publicId'
    | '/members/_tabs/deactivated'
    | '/members/_tabs/pending'
    | '/members/_tabs/rejected'
    | '/members/_tabs/unclaimed'
    | '/my/_tabs/contacts'
    | '/my/_tabs/details'
    | '/my/_tabs/preferences'
    | '/my/_tabs/profile'
    | '/my/_tabs/security'
    | '/my/_tabs/waiver'
    | '/my/gear/cart'
    | '/feedback/_tabs/'
    | '/gear/loans/'
    | '/members/_tabs/'
    | '/my/gear/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessRoute: typeof AccessRoute
  AlbumRoute: typeof AlbumRoute
  AntiHazingRoute: typeof AntiHazingRoute
  AuditRoute: typeof AuditRoute
  ConstitutionRoute: typeof ConstitutionRoute
  DeactivatedRoute: typeof DeactivatedRoute
  DisclaimerRoute: typeof DisclaimerRoute
  FeedbackRoute: typeof FeedbackRouteWithChildren
  GazetteRoute: typeof GazetteRouteWithChildren
  GearRoute: typeof GearRouteWithChildren
  GearCaveRoute: typeof GearCaveRoute
  HealthRoute: typeof HealthRoute
  HistoryRoute: typeof HistoryRoute
  LegalRoute: typeof LegalRoute
  MembersRoute: typeof MembersRouteWithChildren
  MembershipRoute: typeof MembershipRoute
  MyRoute: typeof MyRouteWithChildren
  NondiscriminationRoute: typeof NondiscriminationRoute
  OpenSourceRoute: typeof OpenSourceRoute
  PoliciesRoute: typeof PoliciesRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  SettingsRoute: typeof SettingsRoute
  SignInRoute: typeof SignInRoute
  TermsRoute: typeof TermsRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  WaiverRoute: typeof WaiverRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  RegisterPendingRoute: typeof RegisterPendingRoute
  RegisterProfileRoute: typeof RegisterProfileRoute
  AnnouncementsIndexRoute: typeof AnnouncementsIndexRoute
  ApiAccountExportRoute: typeof ApiAccountExportRoute
  ApiAlbumImageSplatRoute: typeof ApiAlbumImageSplatRoute
  ApiAvatarsSplatRoute: typeof ApiAvatarsSplatRoute
  ApiGazettePdfSplatRoute: typeof ApiGazettePdfSplatRoute
  ApiGearThumbnailsSplatRoute: typeof ApiGearThumbnailsSplatRoute
  ApiLandingSplatRoute: typeof ApiLandingSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/waiver': {
      id: '/waiver'
      path: '/waiver'
      fullPath: '/waiver'
      preLoaderRoute: typeof WaiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/open-source': {
      id: '/open-source'
      path: '/open-source'
      fullPath: '/open-source'
      preLoaderRoute: typeof OpenSourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nondiscrimination': {
      id: '/nondiscrimination'
      path: '/nondiscrimination'
      fullPath: '/nondiscrimination'
      preLoaderRoute: typeof NondiscriminationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my': {
      id: '/my'
      path: '/my'
      fullPath: '/my'
      preLoaderRoute: typeof MyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/members': {
      id: '/members'
      path: '/members'
      fullPath: '/members'
      preLoaderRoute: typeof MembersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal': {
      id: '/legal'
      path: '/legal'
      fullPath: '/legal'
      preLoaderRoute: typeof LegalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gear-cave': {
      id: '/gear-cave'
      path: '/gear-cave'
      fullPath: '/gear-cave'
      preLoaderRoute: typeof GearCaveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gear': {
      id: '/gear'
      path: '/gear'
      fullPath: '/gear'
      preLoaderRoute: typeof GearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gazette': {
      id: '/gazette'
      path: '/gazette'
      fullPath: '/gazette'
      preLoaderRoute: typeof GazetteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/disclaimer': {
      id: '/disclaimer'
      path: '/disclaimer'
      fullPath: '/disclaimer'
      preLoaderRoute: typeof DisclaimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deactivated': {
      id: '/deactivated'
      path: '/deactivated'
      fullPath: '/deactivated'
      preLoaderRoute: typeof DeactivatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/constitution': {
      id: '/constitution'
      path: '/constitution'
      fullPath: '/constitution'
      preLoaderRoute: typeof ConstitutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anti-hazing': {
      id: '/anti-hazing'
      path: '/anti-hazing'
      fullPath: '/anti-hazing'
      preLoaderRoute: typeof AntiHazingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album': {
      id: '/album'
      path: '/album'
      fullPath: '/album'
      preLoaderRoute: typeof AlbumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access': {
      id: '/access'
      path: '/access'
      fullPath: '/access'
      preLoaderRoute: typeof AccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/': {
      id: '/my/'
      path: '/'
      fullPath: '/my/'
      preLoaderRoute: typeof MyIndexRouteImport
      parentRoute: typeof MyRoute
    }
    '/gear/': {
      id: '/gear/'
      path: '/'
      fullPath: '/gear/'
      preLoaderRoute: typeof GearIndexRouteImport
      parentRoute: typeof GearRoute
    }
    '/gazette/': {
      id: '/gazette/'
      path: '/'
      fullPath: '/gazette/'
      preLoaderRoute: typeof GazetteIndexRouteImport
      parentRoute: typeof GazetteRoute
    }
    '/announcements/': {
      id: '/announcements/'
      path: '/announcements'
      fullPath: '/announcements/'
      preLoaderRoute: typeof AnnouncementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/profile': {
      id: '/register/profile'
      path: '/register/profile'
      fullPath: '/register/profile'
      preLoaderRoute: typeof RegisterProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register/pending': {
      id: '/register/pending'
      path: '/register/pending'
      fullPath: '/register/pending'
      preLoaderRoute: typeof RegisterPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/gear': {
      id: '/my/gear'
      path: '/gear'
      fullPath: '/my/gear'
      preLoaderRoute: typeof MyGearRouteImport
      parentRoute: typeof MyRoute
    }
    '/my/_tabs': {
      id: '/my/_tabs'
      path: ''
      fullPath: '/my'
      preLoaderRoute: typeof MyTabsRouteImport
      parentRoute: typeof MyRoute
    }
    '/members/waivers': {
      id: '/members/waivers'
      path: '/waivers'
      fullPath: '/members/waivers'
      preLoaderRoute: typeof MembersWaiversRouteImport
      parentRoute: typeof MembersRoute
    }
    '/members/_tabs': {
      id: '/members/_tabs'
      path: ''
      fullPath: '/members'
      preLoaderRoute: typeof MembersTabsRouteImport
      parentRoute: typeof MembersRoute
    }
    '/members/$publicId': {
      id: '/members/$publicId'
      path: '/$publicId'
      fullPath: '/members/$publicId'
      preLoaderRoute: typeof MembersPublicIdRouteImport
      parentRoute: typeof MembersRoute
    }
    '/gear/$publicId': {
      id: '/gear/$publicId'
      path: '/$publicId'
      fullPath: '/gear/$publicId'
      preLoaderRoute: typeof GearPublicIdRouteImport
      parentRoute: typeof GearRoute
    }
    '/gazette/$publicId': {
      id: '/gazette/$publicId'
      path: '/$publicId'
      fullPath: '/gazette/$publicId'
      preLoaderRoute: typeof GazettePublicIdRouteImport
      parentRoute: typeof GazetteRoute
    }
    '/feedback/_tabs': {
      id: '/feedback/_tabs'
      path: ''
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackTabsRouteImport
      parentRoute: typeof FeedbackRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my/gear/': {
      id: '/my/gear/'
      path: '/'
      fullPath: '/my/gear/'
      preLoaderRoute: typeof MyGearIndexRouteImport
      parentRoute: typeof MyGearRoute
    }
    '/members/_tabs/': {
      id: '/members/_tabs/'
      path: '/'
      fullPath: '/members/'
      preLoaderRoute: typeof MembersTabsIndexRouteImport
      parentRoute: typeof MembersTabsRoute
    }
    '/gear/loans/': {
      id: '/gear/loans/'
      path: '/loans'
      fullPath: '/gear/loans/'
      preLoaderRoute: typeof GearLoansIndexRouteImport
      parentRoute: typeof GearRoute
    }
    '/feedback/_tabs/': {
      id: '/feedback/_tabs/'
      path: '/'
      fullPath: '/feedback/'
      preLoaderRoute: typeof FeedbackTabsIndexRouteImport
      parentRoute: typeof FeedbackTabsRoute
    }
    '/my/gear/cart': {
      id: '/my/gear/cart'
      path: '/cart'
      fullPath: '/my/gear/cart'
      preLoaderRoute: typeof MyGearCartRouteImport
      parentRoute: typeof MyGearRoute
    }
    '/my/_tabs/waiver': {
      id: '/my/_tabs/waiver'
      path: '/waiver'
      fullPath: '/my/waiver'
      preLoaderRoute: typeof MyTabsWaiverRouteImport
      parentRoute: typeof MyTabsRoute
    }
    '/my/_tabs/security': {
      id: '/my/_tabs/security'
      path: '/security'
      fullPath: '/my/security'
      preLoaderRoute: typeof MyTabsSecurityRouteImport
      parentRoute: typeof MyTabsRoute
    }
    '/my/_tabs/profile': {
      id: '/my/_tabs/profile'
      path: '/profile'
      fullPath: '/my/profile'
      preLoaderRoute: typeof MyTabsProfileRouteImport
      parentRoute: typeof MyTabsRoute
    }
    '/my/_tabs/preferences': {
      id: '/my/_tabs/preferences'
      path: '/preferences'
      fullPath: '/my/preferences'
      preLoaderRoute: typeof MyTabsPreferencesRouteImport
      parentRoute: typeof MyTabsRoute
    }
    '/my/_tabs/details': {
      id: '/my/_tabs/details'
      path: '/details'
      fullPath: '/my/details'
      preLoaderRoute: typeof MyTabsDetailsRouteImport
      parentRoute: typeof MyTabsRoute
    }
    '/my/_tabs/contacts': {
      id: '/my/_tabs/contacts'
      path: '/contacts'
      fullPath: '/my/contacts'
      preLoaderRoute: typeof MyTabsContactsRouteImport
      parentRoute: typeof MyTabsRoute
    }
    '/members/_tabs/unclaimed': {
      id: '/members/_tabs/unclaimed'
      path: '/unclaimed'
      fullPath: '/members/unclaimed'
      preLoaderRoute: typeof MembersTabsUnclaimedRouteImport
      parentRoute: typeof MembersTabsRoute
    }
    '/members/_tabs/rejected': {
      id: '/members/_tabs/rejected'
      path: '/rejected'
      fullPath: '/members/rejected'
      preLoaderRoute: typeof MembersTabsRejectedRouteImport
      parentRoute: typeof MembersTabsRoute
    }
    '/members/_tabs/pending': {
      id: '/members/_tabs/pending'
      path: '/pending'
      fullPath: '/members/pending'
      preLoaderRoute: typeof MembersTabsPendingRouteImport
      parentRoute: typeof MembersTabsRoute
    }
    '/members/_tabs/deactivated': {
      id: '/members/_tabs/deactivated'
      path: '/deactivated'
      fullPath: '/members/deactivated'
      preLoaderRoute: typeof MembersTabsDeactivatedRouteImport
      parentRoute: typeof MembersTabsRoute
    }
    '/gear/loans/$publicId': {
      id: '/gear/loans/$publicId'
      path: '/loans/$publicId'
      fullPath: '/gear/loans/$publicId'
      preLoaderRoute: typeof GearLoansPublicIdRouteImport
      parentRoute: typeof GearRoute
    }
    '/feedback/_tabs/club': {
      id: '/feedback/_tabs/club'
      path: '/club'
      fullPath: '/feedback/club'
      preLoaderRoute: typeof FeedbackTabsClubRouteImport
      parentRoute: typeof FeedbackTabsRoute
    }
    '/api/landing/$': {
      id: '/api/landing/$'
      path: '/api/landing/$'
      fullPath: '/api/landing/$'
      preLoaderRoute: typeof ApiLandingSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gear-thumbnails/$': {
      id: '/api/gear-thumbnails/$'
      path: '/api/gear-thumbnails/$'
      fullPath: '/api/gear-thumbnails/$'
      preLoaderRoute: typeof ApiGearThumbnailsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gazette-pdf/$': {
      id: '/api/gazette-pdf/$'
      path: '/api/gazette-pdf/$'
      fullPath: '/api/gazette-pdf/$'
      preLoaderRoute: typeof ApiGazettePdfSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/avatars/$': {
      id: '/api/avatars/$'
      path: '/api/avatars/$'
      fullPath: '/api/avatars/$'
      preLoaderRoute: typeof ApiAvatarsSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/album-image/$': {
      id: '/api/album-image/$'
      path: '/api/album-image/$'
      fullPath: '/api/album-image/$'
      preLoaderRoute: typeof ApiAlbumImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/account/export': {
      id: '/api/account/export'
      path: '/api/account/export'
      fullPath: '/api/account/export'
      preLoaderRoute: typeof ApiAccountExportRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FeedbackTabsRouteChildren {
  FeedbackTabsClubRoute: typeof FeedbackTabsClubRoute
  FeedbackTabsIndexRoute: typeof FeedbackTabsIndexRoute
}

const FeedbackTabsRouteChildren: FeedbackTabsRouteChildren = {
  FeedbackTabsClubRoute: FeedbackTabsClubRoute,
  FeedbackTabsIndexRoute: FeedbackTabsIndexRoute,
}

const FeedbackTabsRouteWithChildren = FeedbackTabsRoute._addFileChildren(
  FeedbackTabsRouteChildren,
)

interface FeedbackRouteChildren {
  FeedbackTabsRoute: typeof FeedbackTabsRouteWithChildren
}

const FeedbackRouteChildren: FeedbackRouteChildren = {
  FeedbackTabsRoute: FeedbackTabsRouteWithChildren,
}

const FeedbackRouteWithChildren = FeedbackRoute._addFileChildren(
  FeedbackRouteChildren,
)

interface GazetteRouteChildren {
  GazettePublicIdRoute: typeof GazettePublicIdRoute
  GazetteIndexRoute: typeof GazetteIndexRoute
}

const GazetteRouteChildren: GazetteRouteChildren = {
  GazettePublicIdRoute: GazettePublicIdRoute,
  GazetteIndexRoute: GazetteIndexRoute,
}

const GazetteRouteWithChildren =
  GazetteRoute._addFileChildren(GazetteRouteChildren)

interface GearRouteChildren {
  GearPublicIdRoute: typeof GearPublicIdRoute
  GearIndexRoute: typeof GearIndexRoute
  GearLoansPublicIdRoute: typeof GearLoansPublicIdRoute
  GearLoansIndexRoute: typeof GearLoansIndexRoute
}

const GearRouteChildren: GearRouteChildren = {
  GearPublicIdRoute: GearPublicIdRoute,
  GearIndexRoute: GearIndexRoute,
  GearLoansPublicIdRoute: GearLoansPublicIdRoute,
  GearLoansIndexRoute: GearLoansIndexRoute,
}

const GearRouteWithChildren = GearRoute._addFileChildren(GearRouteChildren)

interface MembersTabsRouteChildren {
  MembersTabsDeactivatedRoute: typeof MembersTabsDeactivatedRoute
  MembersTabsPendingRoute: typeof MembersTabsPendingRoute
  MembersTabsRejectedRoute: typeof MembersTabsRejectedRoute
  MembersTabsUnclaimedRoute: typeof MembersTabsUnclaimedRoute
  MembersTabsIndexRoute: typeof MembersTabsIndexRoute
}

const MembersTabsRouteChildren: MembersTabsRouteChildren = {
  MembersTabsDeactivatedRoute: MembersTabsDeactivatedRoute,
  MembersTabsPendingRoute: MembersTabsPendingRoute,
  MembersTabsRejectedRoute: MembersTabsRejectedRoute,
  MembersTabsUnclaimedRoute: MembersTabsUnclaimedRoute,
  MembersTabsIndexRoute: MembersTabsIndexRoute,
}

const MembersTabsRouteWithChildren = MembersTabsRoute._addFileChildren(
  MembersTabsRouteChildren,
)

interface MembersRouteChildren {
  MembersPublicIdRoute: typeof MembersPublicIdRoute
  MembersTabsRoute: typeof MembersTabsRouteWithChildren
  MembersWaiversRoute: typeof MembersWaiversRoute
}

const MembersRouteChildren: MembersRouteChildren = {
  MembersPublicIdRoute: MembersPublicIdRoute,
  MembersTabsRoute: MembersTabsRouteWithChildren,
  MembersWaiversRoute: MembersWaiversRoute,
}

const MembersRouteWithChildren =
  MembersRoute._addFileChildren(MembersRouteChildren)

interface MyTabsRouteChildren {
  MyTabsContactsRoute: typeof MyTabsContactsRoute
  MyTabsDetailsRoute: typeof MyTabsDetailsRoute
  MyTabsPreferencesRoute: typeof MyTabsPreferencesRoute
  MyTabsProfileRoute: typeof MyTabsProfileRoute
  MyTabsSecurityRoute: typeof MyTabsSecurityRoute
  MyTabsWaiverRoute: typeof MyTabsWaiverRoute
}

const MyTabsRouteChildren: MyTabsRouteChildren = {
  MyTabsContactsRoute: MyTabsContactsRoute,
  MyTabsDetailsRoute: MyTabsDetailsRoute,
  MyTabsPreferencesRoute: MyTabsPreferencesRoute,
  MyTabsProfileRoute: MyTabsProfileRoute,
  MyTabsSecurityRoute: MyTabsSecurityRoute,
  MyTabsWaiverRoute: MyTabsWaiverRoute,
}

const MyTabsRouteWithChildren =
  MyTabsRoute._addFileChildren(MyTabsRouteChildren)

interface MyGearRouteChildren {
  MyGearCartRoute: typeof MyGearCartRoute
  MyGearIndexRoute: typeof MyGearIndexRoute
}

const MyGearRouteChildren: MyGearRouteChildren = {
  MyGearCartRoute: MyGearCartRoute,
  MyGearIndexRoute: MyGearIndexRoute,
}

const MyGearRouteWithChildren =
  MyGearRoute._addFileChildren(MyGearRouteChildren)

interface MyRouteChildren {
  MyTabsRoute: typeof MyTabsRouteWithChildren
  MyGearRoute: typeof MyGearRouteWithChildren
  MyIndexRoute: typeof MyIndexRoute
}

const MyRouteChildren: MyRouteChildren = {
  MyTabsRoute: MyTabsRouteWithChildren,
  MyGearRoute: MyGearRouteWithChildren,
  MyIndexRoute: MyIndexRoute,
}

const MyRouteWithChildren = MyRoute._addFileChildren(MyRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessRoute: AccessRoute,
  AlbumRoute: AlbumRoute,
  AntiHazingRoute: AntiHazingRoute,
  AuditRoute: AuditRoute,
  ConstitutionRoute: ConstitutionRoute,
  DeactivatedRoute: DeactivatedRoute,
  DisclaimerRoute: DisclaimerRoute,
  FeedbackRoute: FeedbackRouteWithChildren,
  GazetteRoute: GazetteRouteWithChildren,
  GearRoute: GearRouteWithChildren,
  GearCaveRoute: GearCaveRoute,
  HealthRoute: HealthRoute,
  HistoryRoute: HistoryRoute,
  LegalRoute: LegalRoute,
  MembersRoute: MembersRouteWithChildren,
  MembershipRoute: MembershipRoute,
  MyRoute: MyRouteWithChildren,
  NondiscriminationRoute: NondiscriminationRoute,
  OpenSourceRoute: OpenSourceRoute,
  PoliciesRoute: PoliciesRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  SettingsRoute: SettingsRoute,
  SignInRoute: SignInRoute,
  TermsRoute: TermsRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  WaiverRoute: WaiverRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  RegisterPendingRoute: RegisterPendingRoute,
  RegisterProfileRoute: RegisterProfileRoute,
  AnnouncementsIndexRoute: AnnouncementsIndexRoute,
  ApiAccountExportRoute: ApiAccountExportRoute,
  ApiAlbumImageSplatRoute: ApiAlbumImageSplatRoute,
  ApiAvatarsSplatRoute: ApiAvatarsSplatRoute,
  ApiGazettePdfSplatRoute: ApiGazettePdfSplatRoute,
  ApiGearThumbnailsSplatRoute: ApiGearThumbnailsSplatRoute,
  ApiLandingSplatRoute: ApiLandingSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
