import { defineConfig } from "vitest/config";

// Orchestrates the two Vitest projects:
//   - `vitest.workers.config.ts` runs server-side tests inside the
//     @cloudflare/vitest-pool-workers runtime (real workerd + Miniflare D1).
//   - `vitest.dom.config.ts` runs component tests in jsdom with Testing
//     Library.
// Each project owns its own setup, environment, and include glob; this file
// just lists them so `pnpm --filter ucmc-web test` covers both pools in one
// command.
export default defineConfig({
  test: {
    projects: ["./vitest.workers.config.ts", "./vitest.dom.config.ts"],

    /**
     * Coverage is a REPORT, not a gate — `pnpm test:coverage`, and a
     * weekly CI artifact. No thresholds: setting one before a baseline
     * exists picks a number out of the air, and a threshold that fails
     * the build teaches people to write tests that execute lines rather
     * than tests that assert things.
     *
     * **`istanbul`, not the default `v8`, is mandatory here.** V8
     * coverage is unsupported in @cloudflare/vitest-pool-workers, which
     * is where the entire server-side suite runs — so the default
     * provider reports nothing for the half of the codebase that matters
     * most. Istanbul instruments at transform time, which works in both
     * pools.
     * https://developers.cloudflare.com/workers/testing/vitest-integration/known-issues/
     */
    coverage: {
      provider: "istanbul",
      reporter: ["text-summary", "html", "json-summary"],
      reportsDirectory: "./coverage",
      include: ["src/**/*.{ts,tsx}"],
      exclude: [
        // Generated by @tanstack/router-plugin; never hand-edited, so
        // its coverage number is noise (see CLAUDE.md).
        "src/routeTree.gen.ts",
        // Vendored shadcn catalog — added by the CLI, kept whole so its
        // add/update flow stays intact. Same rationale as its `entry`
        // in knip.config.ts.
        "src/components/ui/**",
        // Tests, stories, and the auth stub that exists only for them.
        "src/**/__tests__/**",
        "src/**/*.stories.tsx",
        "src/test-support/**",
        // One-line handlers that dynamic-import their action. The action
        // is what tests call directly (see .claude/rules/testing.md), so
        // counting the shells measures the boundary, not the logic.
        "src/**/*-fns.ts",
      ],
    },
  },
});
