/**
 * Local D1 seed script.
 *
 * Reads SEED_ADMIN_EMAIL from `.env.local` and promotes that email to
 * `system_admin` on the local Miniflare D1 database. Idempotent via
 * INSERT OR IGNORE — safe to re-run. Exits cleanly if SEED_ADMIN_EMAIL
 * is unset.
 *
 * Does NOT touch remote environments. For dev/prod sysadmin seeding,
 * trigger the `seed-admin.yml` GitHub Action from the Actions tab —
 * that path uses GitHub environment protection and is auditable.
 *
 * Usage: pnpm --filter ucmc-web db:seed:local
 */
/* eslint-disable no-console -- this IS a CLI whose job is to log. */
import { execSync } from "node:child_process";
import { randomUUID } from "node:crypto";
import { existsSync, readFileSync, unlinkSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { uuidv7 } from "uuidv7";

import { generateUserPublicId } from "../src/server/auth/ids.ts";

const SCRIPT_DIR = dirname(fileURLToPath(import.meta.url));
const WEB_DIR = resolve(SCRIPT_DIR, "..");
const DB_NAME = "ucmc-web-dev";
// Intentionally stricter than a general-purpose email regex: the allowed
// character classes contain no SQL metacharacters (no `'`, `;`, `--`,
// etc.), which is defense-in-depth on top of the sqlQuote escaping below.
// Accepts practically all real-world email formats in exchange.
const EMAIL_RE = /^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$/;

/**
 * Minimal dotenv parser. Handles `KEY=value` lines, ignores blanks and
 * lines starting with `#`. Does NOT handle quoted values with escape
 * sequences — `.env.local` values in this project are plain strings.
 */
function parseDotenv(path: string): Partial<Record<string, string>> {
  if (!existsSync(path)) {
    return {};
  }
  const out: Partial<Record<string, string>> = {};
  for (const raw of readFileSync(path, "utf8").split("\n")) {
    const line = raw.trim();
    if (!line || line.startsWith("#")) {
      continue;
    }
    const eq = line.indexOf("=");
    if (eq === -1) {
      continue;
    }
    const key = line.slice(0, eq).trim();
    const value = line.slice(eq + 1).trim();
    if (key) {
      out[key] = value;
    }
  }
  return out;
}

/** Escape a value for embedding in a SQLite single-quoted string literal. */
function sqlQuote(value: string): string {
  return `'${value.replace(/'/g, "''")}'`;
}

function main(): void {
  const envPath = join(WEB_DIR, ".env.local");
  const env = parseDotenv(envPath);
  const rawEmail = env.SEED_ADMIN_EMAIL?.trim().toLowerCase();

  if (!rawEmail) {
    console.log(
      `✦ SEED_ADMIN_EMAIL is not set in ${envPath}. Skipping admin seed.`,
    );
    return;
  }
  if (!EMAIL_RE.test(rawEmail)) {
    console.error(
      `✗ SEED_ADMIN_EMAIL=${rawEmail} doesn't look like a valid email. Aborting.`,
    );
    process.exit(1);
  }

  const userId = `user_${uuidv7()}`;
  const publicId = generateUserPublicId();
  const userEmailId = `uem_${uuidv7()}`;
  const nowMs = Date.now();
  const email = sqlQuote(rawEmail);

  // Idempotent four-step seed. Email lives in `user_emails`, so the
  // `users` row no longer collides on email — without an explicit
  // guard we'd insert a fresh users row on every run and orphan the
  // owning account when the email was already claimed. The fix is
  // step 1: insert into `users` ONLY if the email is unclaimed.
  //
  // 1. INSERT INTO users …WHERE NOT EXISTS user_emails.email — creates
  //    the user row only if the email isn't already attached somewhere.
  // 2. INSERT OR IGNORE INTO user_emails — attaches the seed email and
  //    marks it primary. No-op when the email already belongs to
  //    someone (and step 1 was a no-op too); the rest of the script
  //    promotes that existing owner.
  // 3. UPDATE users …gated on status — if a prior registration left
  //    the owner as 'pending' or 'rejected', promote to 'approved'.
  // 4. INSERT OR IGNORE INTO user_roles — grant system_admin to whoever
  //    owns the email (the owner of the user_emails row, whether new
  //    or pre-existing).
  const sql = `-- Generated by apps/web/drizzle/seed.ts on ${new Date().toISOString()}
INSERT INTO users (id, public_id, status, approved_at, created_at)
SELECT ${sqlQuote(userId)}, ${sqlQuote(publicId)}, 'approved', ${nowMs}, ${nowMs}
WHERE NOT EXISTS (SELECT 1 FROM user_emails WHERE email = ${email});
INSERT OR IGNORE INTO user_emails (id, user_id, email, is_primary, verified_at, created_at)
VALUES (${sqlQuote(userEmailId)}, ${sqlQuote(userId)}, ${email}, 1, ${nowMs}, ${nowMs});
UPDATE users
SET status = 'approved', approved_at = ${nowMs}
WHERE id IN (SELECT user_id FROM user_emails WHERE email = ${email})
  AND status <> 'approved';
INSERT OR IGNORE INTO user_roles (user_id, role_id)
SELECT user_id, 'role_system_admin' FROM user_emails WHERE email = ${email};
`;

  const tempFile = join(tmpdir(), `ucmc-seed-${randomUUID()}.sql`);
  writeFileSync(tempFile, sql, "utf8");

  try {
    console.log(
      `→ Promoting ${rawEmail} to system_admin on ${DB_NAME} (local)`,
    );
    execSync(
      `pnpm exec wrangler d1 execute ${DB_NAME} --local --file ${tempFile}`,
      { cwd: WEB_DIR, stdio: "inherit" },
    );
    console.log("✔ Seed complete.");
  } finally {
    try {
      unlinkSync(tempFile);
    } catch {
      // Best-effort cleanup — leaving a file in /tmp isn't a problem.
    }
  }
}

main();
