-- Seed the four newly-dynamic public pages with markdown converted
-- from the LegalSection[] arrays they previously consumed in
-- `apps/web/src/config/legal.ts`. Sections are rendered as `##`
-- headings; section paragraphs become normal markdown paragraphs;
-- LegalSection.bullets and LegalSection.references both render as
-- bullet lists. Generated by `scripts/convert-legal-to-markdown.ts`
-- (deleted after use); reproducible by re-running that script
-- against the legal.ts state at this commit.

INSERT OR IGNORE INTO markdown_pages (slug, markdown) VALUES
  ('policies',
   '## Gear checkout

Access to club gear requires three things in place before checkout: (1) active UCMC membership with the $20-per-semester or $60-per-year equipment fee paid, (2) a current paper waiver on file with the Treasurer, completed at least one week before the first trip on which the gear will be used, and (3) attendance at a club meeting or coordination with the Equipment Manager to arrange the actual handoff.

Gear may be checked out for personal use related to UCMC activities. The standard cycle is Wednesday after the meeting through the following Wednesday at 6:45 PM, with returns due one hour before the next meeting. The Equipment Manager keeps a written record of every checkout; the digital record at /gear is the source of truth.

Returned gear must be clean, dry, and in working condition. Damage discovered at return time is logged on the loan record; minor damage from normal use is part of running a club gear cave and does not generate fines.

## Gear — fines and consequences

Members who keep gear past the due date, return gear damaged from misuse, or lose gear are fined. The minimum fine is $5 per item per week overdue; the maximum is the replacement cost of the item. Unpaid gear fines block participation in future trips and can be reported to the University, which may withhold transcripts and registration until the balance is cleared. Gear unreturned after one month may be reported to UC Public Safety as theft.

If you damage or lose something on a trip, tell an officer. Honest, prompt disclosure is treated very differently from an officer discovering it weeks later.

## Whitewater participation — overview

UCMC whitewater trips run on a three-tier paddler skill model: Novice, Intermediate, and Advanced. The tier determines what equipment a paddler may access and what level of supervision is required. Personal Floatation Devices (PFDs) and helmets are open to every paddler regardless of tier — there is no scenario in which a UCMC paddler is on the water without both.

Tier assignment is made by the Trip Coordinator in consultation with experienced paddlers; certifications from outside organizations are recognized but the Trip Coordinator''s judgment on UCMC trips is final. Policy may change between seasons; the current text on this page is authoritative.

## Whitewater — Novice tier

A Novice paddler may participate on Class I–II water under direct supervision of an Advanced paddler at a 1:1 ratio (one Advanced paddler per Novice in a boat) unless the Novice carries a current swiftwater or whitewater certification from an outside organization.

Before paddling a boat (as opposed to riding in a raft), a Novice must demonstrate a wet exit to a current officer or designated trainer. Boats may not be checked out for Novice trips without this demonstration on file.

## Whitewater — Intermediate tier

Intermediate paddlers must demonstrate a reliable river roll (a 2-of-3 success rate is the working threshold), complete UCMC''s whitewater fundamentals course ("WW101" in club slang), and pass a river-knowledge approval administered by an Advanced paddler. Intermediate paddlers may run Class II–III water without 1:1 supervision but in a group with at least one Advanced paddler.

## Whitewater — Advanced tier

Advanced paddlers can confidently paddle Class III water and have completed or can demonstrate equivalent training to a swiftwater rescue / river-rescue course. Advanced paddlers may lead trips, supervise Novices, and access the full whitewater gear inventory including specialized boats.

## Climbing participation — overview

UCMC climbing uses a parallel three-tier model: Novice, Intermediate, and Advanced. Harnesses and helmets are open to every climber. Tier assignment is made by the Trip Coordinator and experienced climbers, with outside certifications recognized. Policy may change between seasons.

## Climbing — Novice tier

A Novice climber must demonstrate competency tying a figure-eight follow-through and putting on a harness correctly before climbing any UCMC route. Novices climb under direct supervision of an Advanced climber at 1:1 ratio unless they carry a current climbing certification from an outside organization. Top-rope only — no lead climbing.

## Climbing — Intermediate tier

Intermediate climbers may top-rope independently after completing UCMC''s introductory climbing course. They may build a top-rope anchor only with an Advanced climber checking the system. Lead climbing remains restricted to the Advanced tier.

## Climbing — Advanced tier

Advanced climbers may lead sport routes and (with separate trad-specific training) lead trad routes on UCMC trips. Advanced climbers accept responsibility for the trip''s communication with the rest of UCMC: itinerary submission, emergency-contact sheet, and post-trip debrief. The Trip Coordinator may withdraw advanced privileges for safety-relevant policy violations.'),
  ('scholarships',
   '## Steve Must Memorial Scholarship

UCMC established the Outdoor Leadership Scholarship in 1997 to underwrite undergraduate members attending professional wilderness and outdoor education programs. In 1999 the fund was renamed in memory of Steve Must, a beloved 1980s-era club member who went on to spend years in the Pacific Northwest mountaineering with the legendary Fred Beckey.

In the words of the program: "The goal of the UCMC Steve Must Memorial Scholarship (SMMS) is to further develop the outdoor leadership skills of UCMC student members who have proven commitment and leadership potential." Recipients are expected to return to the club and share what they learn — it is an investment, not a reward.

- [Steve Must — in memoriam](/history#steve-must-in-memoriam)

## Eligibility

Applicants must be matriculated UC undergraduates in good standing with UCMC, with at least one year of undergraduate study remaining, a UCMC membership of at least 8 months at the time the funded course begins, and an academic record showing both:

- Cumulative GPA of 2.25 or higher (maintained through the award);
- GPA of 2.00 or higher in each of the two quarters/semesters immediately preceding the course;
- Evidence that the applicant has first applied for any other available scholarships or financial aid;
- Consistent demonstration of leadership potential and commitment to UCMC.

## Application timeline

Applications are reviewed twice per academic year by the Scholarship Committee. The cycles align with when courses tend to run.

- Fall (for late-October-through-February courses): budget announced in Week 4; applications open Weeks 4–8; selections announced Week 9; recipients accept by Week 11.
- Spring (for March-through-September courses): remaining funds announced in Fall Week 13; applications open Fall Week 14 through Spring Week 4; selections announced Week 5; recipients accept by Week 7.
- Applications outside these windows are reviewed case-by-case.

## Formal proposal

Every application is a formal written proposal submitted to the Executive and Scholarship Committees. It must include:

- Course provider description and curriculum, including all prerequisites, costs, and required insurance;
- Documentation showing the applicant meets every provider prerequisite (medical exam, prior certifications, insurance);
- Proof of UC enrollment, current GPA, and active medical insurance;
- Copies of every other scholarship or financial-aid application the applicant has submitted;
- A written plan for how the acquired knowledge will be shared back with UCMC membership (lectures, trip leadership, gear training, Goosedown Gazette articles, etc.);
- A statement of the applicant''s prior UCMC participation, leadership history, and committed service to the club.

## Selection criteria

The committee weighs three questions when ranking proposals:

- What outdoor-leadership development does UCMC currently need?
- Which programs would meet those needs?
- Which candidates are most likely to return their new knowledge to the club?

## Refund policy

Awards are conditional on completing the funded course. "In the event that a scholarship recipient does not successfully complete the course for which the award was designated, the UCMC will require that the award amount be refunded." The Treasurer manages refund arrangements case-by-case.

## Selection committee

The Scholarship Committee is a five-person body appointed by the Executive Committee: two UCMC alumni, two current student members, and the UCMC faculty advisor. Membership is documented in the bylaws and rotates annually as roles change.

## Past recipients

A partial record of past awards — names, courses, and (where available) reflections written by the recipient — is preserved as historical context. The first scholarship (1997) was an informal collection from members and officers; the formal program with its current rules begins in 1999.

- Emily Hannan, Spring 2020 — AAI Alpinism 1 on Mount Baker (Steve Must Memorial Scholarship).
- Several members, Fall 2002 — WFR (Wilderness First Responder); fees offset by the scholarship.
- Robert Sexton, Summer 2000 — ACA Whitewater Kayaking Instructor.
- Annelies Koob and three others, Spring 1999 — WMA Wilderness First Responder (72-hour course).
- Robert Sexton, Spring 1999 — ACA Swiftwater Rescue Instructor.
- Jeremy Sibert, Summer 1997 — NOLS Mountaineering in Alaska (the first, informal UCMC scholarship).

- [Robert Sexton — recipient documentation (1 of 2)](/scholarships/sexton_01.pdf)
- [Robert Sexton — recipient documentation (2 of 2)](/scholarships/sexton_02.pdf)
- [Annelies Koob — recipient documentation](/scholarships/koob.pdf)

## How to donate

Donations are routed through the UC Foundation, which is a 501(c)(3) tax-exempt entity — gifts are tax-deductible to the extent allowed by law. Many employers offer matching programs for gifts to non-profits; ask your HR department.

For mailed gifts: make checks payable to The UC Foundation. On the memo line, write: UCMC Steve Must Scholarship (F102341). Mail to The University of Cincinnati Foundation, PO Box 19970, Cincinnati, OH 45219-0970. A short cover letter noting the gift supports the "UC Mountaineering Club Steve Must Memorial Scholarship (F102341)" helps the Foundation''s mailroom route it correctly.

For online gifts: the canonical online-giving page for the Steve Must Memorial Scholarship lives on the UC Foundation site, but because "UCMC" inside the University of Cincinnati can refer to either the Mountaineering Club or UC Health / UC Medical Center, the legacy /UCMC vanity URL is ambiguous and not currently verified as our scholarship''s landing page. Please ask the UCMC Treasurer for the current verified online-giving URL before sending an online gift, or fall back to the mailed-check instructions above — the F102341 fund identifier on the memo line is unambiguous.'),
  ('gear_cave',
   '## What it is

The gear cave is a closet of club-owned outdoor equipment that any active UCMC member can borrow for trips. We''ve been accumulating gear since the founders'' first REI order in 1972; today it covers most of the categories the club actively does trips in.

The point of the cave isn''t a substitute for owning your own kit — it''s a way to get on a trip *before* you''ve decided whether kayaking or caving is going to be your thing. Members regularly borrow for a few seasons, decide they''re hooked, and start building their own kit.

## Access — who can borrow

Borrowing requires three things in place: (1) an active UCMC membership in good standing with the annual equipment fee paid (per Bylaw §6.1, $60 per year or $20 per semester at the time of the bylaws'' last amendment — confirm the current fee schedule with the Treasurer), (2) a current paper waiver on file with the Treasurer, completed at least one week before your first trip, and (3) coordination with the Equipment Manager to actually pick up the gear.

The waiver is a paper form. Once signed, it covers an entire year of trips; you don''t repeat it per trip. The Treasurer holds the signed paper off-platform.

- [Membership and dues](/membership)
- [Waiver](/waiver)
- [Gear checkout policy](/policies)

## What we own

A high-level overview of the club''s inventory. Members can browse the full live inventory after signing in; officers maintain it at /gear.

- Backpacking and camping — tents (2–6 person), sleeping bags rated for three-season use, sleeping pads, canister and liquid-fuel stoves, water filtration, cooking kits, headlamps.
- Climbing — harnesses, helmets, climbing shoes in a range of sizes, top-rope-length and lead-length ropes, quickdraws, slings, locking and non-locking carabiners, belay/rappel devices, a modest trad rack.
- Mountaineering and ice — ice axes, crampons, alpine helmets, avalanche transceivers (when relevant), probes, shovels.
- Caving — caving-rated helmets, primary headlamps and backups, vertical-caving ascenders and descenders, harnesses, gloves, knee pads.
- Whitewater — whitewater kayaks (several boats), touring kayaks, rafts and rescue rafts, PFDs in adult sizes, helmets, paddles, throw bags, breakdown rescue gear.
- Reference library — a small but growing collection of guidebooks, route reference materials, and outdoor-skills books in the cave for member reference.
- Miscellaneous — first-aid kits, two-way radios, coolers, group tarps, group kitchen kits.

## How to actually check something out

The standard cycle is the Wednesday meeting through the following Wednesday at 6:45 PM, with returns due one hour before the next meeting. Talk to the Equipment Manager at a meeting (or via the contact email in the footer) to arrange a checkout; the digital record at /gear is the source of truth.

Returns must be clean, dry, and in working condition. Minor wear-and-tear from honest use is just the cost of running a club gear cave; damage from misuse and overdue returns are fined per the gear policy. Lost or unreturned gear after one month may be reported as theft. If something goes wrong on a trip, tell an officer.

- [Gear checkout policy](/policies)'),
  ('resources',
   '## Trip planning documents

Operational paper forms used on club trips. The Trip Leader Checklist and Trip Sign-Up Sheet are intended for trip leaders running an upcoming trip; the Packing List is a starting point for any beginner heading out the first time; the Emergency Contact Form is filled per-trip and brought to the trailhead.

The paper waiver itself is on the membership page — once it''s signed it stays with the Treasurer; you do not "submit" it on a trip.

- [Packing list (PDF)](/resources/packing_list.pdf)
- [Trip sign-up sheet (PDF)](/resources/ucmc_trip_sheet.pdf)
- [Trip leader checklist (PDF)](/resources/ucmc_trip_leader_checklist.pdf)
- [Emergency contact form (PDF)](/resources/emergency_contact_form.pdf)
- [Paper waiver](/waiver)

## What to pack — whitewater

Suggested packing for a spring/summer/fall car-camping paddle trip in the Ohio / Kentucky / West Virginia region. UCMC provides PFDs, helmets, and boats; everything else is on you.

- PFD (provided) and helmet (provided) — non-negotiable, on the water at all times.
- Swimwear plus a wetsuit when combined air+water temperature is below 100°F. Hypothermia kills paddlers faster than drowning does.
- River shoes (closed-toe; old sneakers are fine). No bare feet, no flip-flops.
- Synthetic or wool insulating layers; cotton is forbidden for paddling clothing because it sheds heat catastrophically when wet.
- Wool or synthetic socks; a complete dry change of clothes in a dry bag for after the takeout.
- Throw rope and a couple of carabiners (the trip leader will have these but redundancy is good).
- Water bottle accessible on-deck (closed-toe carabiner clip works) and food in a dry bag.
- Sunscreen, sunglasses with retainer leash, basic first-aid kit.

## What to pack — caving

Suggested packing for caves in Kentucky and Indiana. Local caves run ~55°F year-round with high humidity and potential wading or swimming sections. Hypothermia is the dominant risk; even on a warm summer day you will get cold underground.

- Helmet with attached headlamp (own batteries; bring spares) plus a fully independent backup light. A flashlight in your pocket counts; relying solely on a phone does not.
- Crush-resistant water bottle (Nalgene-style). Hydration bladders get pinched in tight passages.
- Synthetic underwear and base layers; cotton is forbidden underground for the same hypothermia reason as paddling.
- Sturdy ankle-high boots or shoes you don''t mind ruining. Cave mud is permanent.
- Knee pads (gardening pads work) and work gloves.
- Small cave pack you don''t mind dragging through mud and tight spots.
- Towel and a complete dry change of clothes left in the car.
- Contact lenses, not glasses, if you have the option — glasses fog and fall off.

## External training organizations

Reputable outdoor and wilderness-training organizations whose courses UCMC members frequently attend, particularly Steve Must Memorial Scholarship recipients. UCMC and the Scholarship Committee make no endorsement or guarantee about the quality of these specific programs in any given year — do your own due diligence.

- [National Outdoor Leadership School (NOLS)](https://www.nols.edu/)
- [Outward Bound](https://www.outwardbound.org/)
- [Wilderness Medical Associates](https://wildmed.com/)
- [SOLO — Stonehearth Open Learning Opportunities](https://soloschools.com/)
- [American Mountain Guides Association (AMGA)](https://amga.com/)
- [Seneca Rocks Climbing School](https://climbseneca.com/)
- [Colorado Mountain School](https://coloradomountainschool.com/)
- [Nantahala Outdoor Center](https://noc.com/lessons-training)
- [National Cave Rescue Commission](http://ncrc.info/)

## UC student support

UCMC trips can take you a long way from home and from your routine support network. If something happens, on a trip or otherwise, these are the on-campus and Cincinnati-area resources we''d encourage you to use. Talk to any officer if you''d like help reaching out.

- [UC Counseling and Psychological Services (CAPS) — 513-556-0648](https://www.uc.edu/campus-life/caps.html)
- [UC Office of Equal Opportunity & Access](https://www.uc.edu/about/equity-inclusion/equal-opportunity.html)
- [UC Title IX office](https://www.uc.edu/about/equity-inclusion/gender-equity/title-ix.html)
- [UC LGBTQ Center](https://www.uc.edu/campus-life/lgbtq.html)
- [UC Women''s Center](https://www.uc.edu/campus-life/womens-center.html)
- [Bearcat Pantry (main campus)](https://www.uc.edu/campus-life/dean-of-students/bearcats-pantry.html)
- [Women Helping Women hotline — 513-381-5610](https://www.womenhelpingwomen.org/)
- [National Alliance on Mental Illness (SW Ohio) — 513-351-3500](https://namiswoh.org/)
- [Freestore Foodbank](https://freestorefoodbank.org/)

## Regional outdoor links

Hand-curated subset of the legacy useful-links directory. Skewed toward Ohio / Kentucky / Indiana resources, plus national orgs that consistently come up on UCMC trips.

- [AllTrails (route maps)](https://www.alltrails.com/)
- [Mountain Project (climbing route database)](https://www.mountainproject.com/)
- [American Whitewater (river data + advocacy)](https://www.americanwhitewater.org/)
- [USGS Real-Time Water Data (river gauges)](https://waterdata.usgs.gov/nwis/rt)
- [Mountain-Forecast.com (alpine weather)](https://www.mountain-forecast.com/)
- [Red River Gorge Geological Area](http://www.redrivergorge.com/)
- [Red River Gorge Climbers'' Coalition](http://www.rrgcc.org/)
- [Mammoth Cave National Park](https://www.nps.gov/maca/index.htm)
- [Daniel Boone National Forest](https://www.fs.usda.gov/dbnf/)
- [Greater Cincinnati Grotto (caving)](http://www.gcgcavers.com/)
- [National Speleological Society](https://caves.org/)
- [Ohio State Parks](https://parks.ohiodnr.gov/)
- [Wayne National Forest (Ohio)](https://www.fs.usda.gov/wayne)
- [Cuyahoga Valley National Park](https://www.nps.gov/cuva/index.htm)
- [Hoosier National Forest (Indiana)](https://www.fs.usda.gov/hoosier)
- [Indiana Dunes National Park](https://www.nps.gov/indu/index.htm)
- [New River Gorge National Park & Preserve](https://www.nps.gov/neri/index.htm)
- [Leave No Trace](https://lnt.org/)
- [American Alpine Club](https://americanalpineclub.org/)
- [The Access Fund (climbing advocacy)](https://www.accessfund.org/)
- [Free Campsites](https://freecampsites.net/)
- [Roads Rivers and Trails (Cincinnati outfitter)](https://roadsriversandtrails.com/)
- [Benchmark Outfitters (Cincinnati outfitter)](https://www.benchmarkoutfitter.com/)
- [REI](https://www.rei.com/)');
